### ISSUE TITLE
cipher is immutable but its method takes mutable self

### ISSUE THREAD

**Issue by keepsimple1** [RustCrypto/block-ciphers#132]
https://github.com/RustCrypto/block-ciphers/blob/bc219f915e156481c738285b307b6719be3aa2c3/block-modes/src/lib.rs#L58-L59

In above, `cipher` is immutable, but `encrypt_vec` takes mutable self, see here:
https://github.com/RustCrypto/block-ciphers/blob/bc219f915e156481c738285b307b6719be3aa2c3/block-modes/src/traits.rs#L71

I'm wondering how this works?

**Comment by tarcieri** [comment]
It consumes `self`. The `mut` is an implementation detail of the local binding after `self` is consumed.

**Comment by keepsimple1** [comment]
I didn't know Rust allow that.  That said, why consumes `self`?  why not using a reference?

The types that implement this trait might not be `Copy`.  with the current method, it could cause problems when `cipher` is part of a struct, when the struct itself is not moved.

**Comment by tarcieri** [comment]
Because CBC mode requires padding for security. The one-shot API prevents misuse.

> it could cause problems when cipher is part of a struct

Clone the cipher type before instantiating it.

**Comment by newpavlov** [comment]
Note that creation of block modes from ciphers is a really cheap operation and cloning a cipher instance is not too costly either.

But nevertheless, I wonder if we can add `impl<T: BlockCipher> BlockCipher for &T`, this could make it possible to instantiate a block mode using block cipher reference (although we would have to slightly change `BlockCipher` definition to accommodate for that).

**Comment by keepsimple1** [comment]
> Because CBC mode requires padding for security. The one-shot API prevents misuse.

I don't understand. It seems padding is done using the `buf` / `block`, not `self`:

https://github.com/RustCrypto/block-ciphers/blob/bc219f915e156481c738285b307b6719be3aa2c3/block-modes/src/traits.rs#L77-L85

Maybe I'm missing something?

**Comment by tarcieri** [comment]
For security reasons:

- IVs *cannot* be reused.
- the last block encrypted must be padded.

The encryptor is stateful, and for e.g. CBC mode begins with an IV and then uses the previous (encrypted) block as the IV of the next.

There's no further secure operations possible after completing a CBC mode encryption. If we were to reset the instance, it would let you reuse an IV. You can't add any more blocks, because padding is used to signal the end of the message.

If you want to encrypt a new message, you *must* start over with a new IV.
