### ISSUE TITLE
Make `expand` and `encrypt` public.

### ISSUE THREAD

**Issue by qm3ster** [RustCrypto/block-ciphers#34]
I need to do just one round of encryption, to replicate something like this:
```js
var key = Aes.cipher(pwBytes, Aes.keyExpansion(pwBytes));
```
Afaik I currently cannot do that, since those are in a private module.

Hopefully I'm completely wrong and what I need is available in another `RustCrypto` crate.

**Comment by newpavlov** [comment]
Unfortunately this will not be easy. In the case of `aesni` exapnsion, encryption and decryption rounds are [inlined](https://github.com/RustCrypto/block-ciphers/blob/master/aes/aesni/src/aes128/mod.rs#L43) for performance reasons, and in the case of `aes-soft` code is somewhat convoluted. I think your best shot will be to use `aesni` as a reference and write your target function directly. If you'll have any questions I will be glad to answer them!

**Comment by qm3ster** [comment]
IIRC, having it marked `inline` but also exporting it would still inline and fully optimize the version used internally.
Furthermore, it would export not bindings to a "compiled" version but essentially export the AST as part of the metadata, meaning it would even get inlined into consumer crates, giving great performance to unorthodox uses.
Am I totally wrong?

**Comment by newpavlov** [comment]
One round of encryption is just one `_mm_aesenc_si128` call, so I don't think it makes sense to expose wrapper around one intrinsic. As for key expansion, currently intrinsic requires const argument, so I am using [macros](https://github.com/RustCrypto/block-ciphers/blob/master/aes/aesni/src/aes128/expand.rs#L5) because of it. (see this [topic](https://internals.rust-lang.org/t/pre-rfc-const-function-arguments/6709/)) I don't see how it can be cleanly exposed in public API. (especially in the case of AES-192 which has more convoluted key schedule)
