### ISSUE TITLE
BlockMode::decrypt truncates output at first zero byte?

### ISSUE THREAD

**Issue by nickray** [RustCrypto/block-ciphers#70]
Hey,

I'm using this ecosystem as fallback for Aes256Cbc with IV = 0. I guess this means I'm using aes-soft.

The ciphertext I'm getting has underlying plaintext padded with zero bytes to length 64 (e.g. [49, 50, 51, 52, 0, ... 0]). The plaintext output is shortened as if it were a C string (e.g. [49, 50, 51, 52]). While this would be convenient for me, it's unexpected. Is it intended?

My code is more or less
```rust
let mut buffer = request.message.clone();
let zero_iv = [0u8; 16];
let cipher = Aes256Cbc::new_var(&symmetric_key, &zero_iv).unwrap();
let plaintext = cipher.decrypt(&mut buffer).unwrap();
```

Example data:
```python
key = b'\xd3\xf8\xe5f\x94c\xc9\xba\xa4\x97\xee\xe4\x14\xdb$\xd6\x8f\xf7\xac\xbc\xb9\x8e\x19\xca_\x12\x0e#\xc1\xd3(\xd6'
iv = b'\0' * 16
ciphertext = b'u\x1a\nJ\x02\xccl\xb7|\x1f\x91\x16n\xe6}\xcf\x96\x91__\'N6\xee!\x83\xc3\x14d\xb3\xe3;\x7f&j\xd9\xcb\xa6\x95\x8f\xcdz\x84\xc1W\xa8Y\x03\xe4\x8d{\xa3\xc6\x85z\x81\xfa>TPWD\x1d\xe3'
```

**Comment by tarcieri** [comment]
That sounds like there's a padding error in either the ciphertext or the CBC implementation in `block-modes`.

Can you provide the full original plaintext as intended?

**Comment by nickray** [comment]
Sure: `b'1234\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'`.

For context, this is what Chrome sends when you set FIDO2 PIN to `1234`, and Python's `cryptography.hazmat.primitives` deciphers as expected. Shouldn't in any case either deciphering fail with a `BlockModeError`, or the plaintext be the same length as the ciphertext?

**Comment by newpavlov** [comment]
I guess you are using [`ZeroPadding`](https://docs.rs/block-padding/0.1.5/block_padding/enum.ZeroPadding.html), correct? In this case this behavior is intentional. If we are to trust [wiki](https://en.wikipedia.org/wiki/Padding_(cryptography)#Zero_padding), then such behavior is described in ISO/IEC 10118-1 and ISO/IEC 9797-1. My guess is that `hazmat` leaves the trailing zero to keep compatibility with C null-terminated strings (probably because it uses OpenSSL as a backend).
